package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    check(artifactRules == """
        +:allure-report => allure-report
        +:allure-report/history => allure-report/history
    """) {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        +:allure-report => allure-report
        +:allure-report/history => allure-report/history
    """.trimIndent()

    check(allowExternalStatus == false) {
        "Unexpected option value: allowExternalStatus = $allowExternalStatus"
    }
    allowExternalStatus = true

    params {
        add {
            text("env.DURATION", "", allowEmpty = true)
        }
        add {
            text("env.FAILED_TESTS", "", allowEmpty = true)
        }
        add {
            text("env.PASSED_TESTS", "", allowEmpty = true)
        }
    }
}
